### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by Anangaya** [SoftCoil/pipe-monitor#1]
I'm only interested in the last output line so I would like a way to do that or better yet implement a progress bar.

**Comment by morrica** [comment]
Viewing only the last output line is possible by piping standard error to tail using process substitution. See the following stackoverflow answer: https://stackoverflow.com/a/9888720

Adding a progress bar is not possible for a tool that is designed to work where a console is not available. For a similar tool that is designed to work with a console and so can provide a progress bar you may find the Pipe Viewer (pv) command helpful.
